### PR TITLE
feat, added check for module function and test for module function

### PR DESCRIPTION
**Pull request by JonasHUL**
image

### CODE REVIEW

**Comment by oscols** [comment]
Very nice!

**Comment by JonasHUL** [comment]
We had a problem where my vs code modified a lot of files even though I did not modify any files except Checker.py and check-function-always-true.test.

**Comment by JonasHUL** [comment]
Added this to check-function-always-true.test.
[case testModuleAlwaysTrue]
# flags: --python-version 3.6
import math 

if math.sqrt: # E: Module function "sqrt" that has signature "Callable[[Any], float]" could always be true in boolean context
    pass
[builtins fixtures/tuple.pyi]

And added

**Comment by JonasHUL** [comment]
Changed this in Checker.py
Added
image
Removed
image

**Pull request merged**
